# -*- coding: utf-8 -*-
"""src/data/layouts.csv のダミーデータを書き出す。
実データが揃ったら、このスクリプトは不要（CSVを直接編集する）。"""
import csv, os

COLS = ["id","name","kana","genre","author","year","version","url","resources",
        "proxy","consent","chord","shift","os","software","phys_keys","thumb",
        "keyboard","geometry","keymap","keymap_sub","figure","anim",
        "q11","q12","q13","q21","q21c","q22","q23","q31","q32","q4","updated"]

R = lambda **kw: {c: kw.get(c, "") for c in COLS}

ROWS = [
 R(id="oonishi", name="大西配列", kana="おおにしはいれつ", genre="romaji",
   author="大西", year="2021", version="普及版", url="https://example.com/oonishi",
   resources="練習用テキスト^https://example.com/oonishi/text",
   chord="なし", shift="シフトなし",
   os="Windows / macOS / Linux", software="不要", phys_keys="26キー", thumb="不要",
   keyboard="JIS / US", geometry="row",
   keymap="1234567890/|QLU,.FWRYP|EIAO-KTNSH|ZXCV;GDMJB", anim="oonishi",
   q11="同じ指を続けて使う場面を減らし、左右交互に運べるようにしました。",
   q12="母音を左手ホーム段にまとめ、指の移動距離を抑えています。",
   q13="0", q21="0",
   q21c="ローマ字のルールはそのままなので、位置を覚えるだけで済みます。",
   q22="00キー", q23="拗音の入力にSHを使えるようにして、覚える例外を減らしました。",
   q31="100万字統計から開発。QWERTY配列から指の移動距離は約52%、同指の連続は約88%減少します。",
   q32="青空文庫から集めた約100万字のローマ字を頻度分析し、打ちやすいキーほど多く使うよう配置しました。英文の入力効率も英語用の配列と同等の水準です。日英どちらも打つ方に向いています。",
   q4="ローマ字入力である以上、1文字あたりの打鍵数はかな系の配列より多くなります。打鍵数そのものを減らしたい方には向きません。",
   updated="2026年10月1日"),

 R(id="dvorak", name="DVORAK", kana="どぼらっく", genre="romaji",
   author="Dvorak", year="1936", version="—", url="https://example.com/dvorak",
   resources="", proxy="配烈かな", consent="連絡がつかないため未確認",
   chord="なし", shift="シフトなし", os="すべて", software="不要",
   phys_keys="26キー", thumb="不要", keyboard="JIS / US", geometry="row",
   keymap="1234567890-|',.PYFGCRL|AOEUIDHTNS|;QJKXBMWVZ", anim="dvorak",
   q11="母音を左手に集め、左右交互の打鍵になるようにしています。",
   q12="使用頻度の高い文字をホーム段に置いています。",
   q13="1", q21="1", q21c="英文向けの設計なので、日本語では覚え直しが要ります。",
   q22="00キー", q23="—",
   q31="いにしえの新配列。QWERTYから覇権を奪おうと運動を起こすも、その悲願は未だ道半ば。",
   q32="1930年代に英文タイプライター向けに設計された配列です。日本語のローマ字入力に使うと、母音が左手に偏るぶん左右の負担が偏ります。",
   q4="日本語向けに設計された配列ではないため、ローマ字入力での効率は近年の配列に及びません。",
   updated="2026年10月1日"),

 R(id="kakukaku", name="□□配列", kana="かくかくはいれつ", genre="gyodan",
   author="□□", year="2015", version="v1.0", url="https://example.com/kakukaku",
   resources="", chord="なし", shift="前置シフト",
   os="Windows", software="やまぶき", phys_keys="00キー", thumb="不要",
   keyboard="JIS", geometry="row", figure="",
   q11="子音と母音を左右に分け、交互に打てる形にしています。",
   q12="頻出する行段をホーム段に集めています。",
   q13="1", q21="1", q21c="ローマ字の考え方が残るので、乗り換えはなだらかです。",
   q22="00キー", q23="行と段の位置に規則性を持たせました。",
   q31="長文でも指が散らばらず、快適です。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),

 R(id="marumaru", name="〇〇配列", kana="まるまるはいれつ", genre="gyodan",
   author="〇〇", year="2010", version="v2.1", url="https://example.com/marumaru",
   resources="練習帳^https://example.com/marumaru/drill",
   chord="あり", shift="文字キーシフト",
   os="Windows", software="DvorakJ", phys_keys="00キー", thumb="不要",
   keyboard="JIS", geometry="row",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="2", q21="0", q21c="規則性が強いので、覚える量は多くありません。",
   q22="00キー", q23="ここに工夫が入ります。全角50字以内。",
   q31="とにかく覚えやすいのが特徴です。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="", updated="2026年10月1日"),

 R(id="asuasu", name="明日明日配列", kana="あすあすはいれつ", genre="kana",
   author="明日", year="2001", version="v4", url="https://example.com/asuasu",
   resources="", chord="あり", shift="センターシフト",
   os="Windows", software="DvorakJ", phys_keys="00キー", thumb="要",
   keyboard="JIS", geometry="row",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="2", q21="2", q21c="覚える量は多いですが、語のまとまりで手が動きます。",
   q22="00キー", q23="ここに工夫が入ります。全角50字以内。",
   q31="キーの連接がスムーズなので、流れるようなタイピングができます。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),

 R(id="gekkou", name="月光配列", kana="げっこうはいれつ", genre="kana",
   author="月光", year="2004", version="2-263", url="https://example.com/gekkou",
   resources="", chord="なし", shift="前置シフト",
   os="Windows", software="DvorakJ", phys_keys="00キー", thumb="不要",
   keyboard="JIS", geometry="row",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="1", q21="1", q21c="順番に押すだけなので、練習の入口が広いです。",
   q22="00キー", q23="ここに工夫が入ります。全角50字以内。",
   q31="順番に押すだけなので、同時押しが苦手でも始められます。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),

 R(id="shinzouri", name="新草履配列", kana="しんぞうりはいれつ", genre="kana",
   author="草履", year="2012", version="v1.3", url="https://example.com/shinzouri",
   resources="", chord="あり", shift="親指・文字キーシフト",
   os="Windows", software="やまぶき", phys_keys="00キー", thumb="要",
   keyboard="JIS / 分割型", geometry="ortho",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="0", q21="2", q21c="単打が多いので、覚えてしまえば速く打てます。",
   q22="00キー", q23="ここに工夫が入ります。全角50字以内。",
   q31="アルペジオを重視した高効率なカナ配列。単打率の高さに特徴あり。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),

 R(id="battou", name="抜刀式", kana="ばっとうしき", genre="kana",
   author="抜刀", year="2018", version="v3.2", url="https://example.com/battou",
   resources="抜刀式練習帳^https://example.com/battou/drill;導入手順の動画^https://example.com/battou/movie",
   chord="あり", shift="センター・文字キーシフト",
   os="Windows", software="やまぶき", phys_keys="00キー", thumb="要",
   keyboard="分割型 / カラムスタッガード", geometry="column", anim="battou",
   q11="キーの連なりが内側から外側へ流れるよう並べました。",
   q12="頻度の高いかなをホーム段に集め、上段の使用を抑えています。",
   q13="2", q21="2", q21c="覚える量は多いですが、指が形で覚えていきます。",
   q22="00キー", q23="濁音は清音と同じ指で打てるよう対応づけています。",
   q31="考えながら書ける長文向け配列。手書きするようにタイピングできます。",
   q32="小説や記事のように、頭のなかで文を組み立てながら書く用途を想定しています。変換の待ち時間で思考が途切れないよう、句読点と助詞の位置を優先して決めました。本配列で「いろはにほへと」と打っていただくと、指の流れ方が伝わりやすいと思います。",
   q4="速記のように短時間で大量の文字を打つ用途には向きません。同時打鍵を使うため、キーボードによっては入力を取りこぼすことがあります。また、記号や英数字の扱いは標準的な配列に劣ります。",
   updated="2026年10月1日"),

 R(id="ttmode", name="TT-Mode", kana="てぃーてぃーもーど", genre="kanchoku",
   author="TT", year="1985", version="—", url="https://example.com/ttmode",
   resources="", proxy="配烈かな", consent="あり",
   chord="なし", shift="シフトなし", os="Windows / Linux", software="漢直DD ほか",
   phys_keys="99キー", thumb="不要", keyboard="JIS / US", geometry="row",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="1", q21="2", q21c="覚える字数が多く、習得には時間がかかります。",
   q22="", q23="部首の組み立てで覚えられるよう体系立てています。",
   q31="2打鍵で漢字が出るので、変換が必要ありません。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),

 R(id="mimizuku", name="ミミズク式", kana="みみずくしき", genre="sokki",
   author="ミミズク", year="2020", version="v2", url="https://example.com/mimizuku",
   resources="", chord="あり", shift="シフトあり",
   os="専用機", software="専用機", phys_keys="00キー", thumb="要",
   keyboard="専用機（オーソリニア）", geometry="ortho",
   q11="ここに滑らかさのひと言が入ります。全角50字以内。",
   q12="ここに打鍵効率のひと言が入ります。全角50字以内。",
   q13="0", q21="2", q21c="速記の記号体系から覚える必要があります。",
   q22="00キー", q23="ここに工夫が入ります。全角50字以内。",
   q31="熟語の入力が速く、速記のスゴさを実感できる配列です。",
   q32="ここに補足が入ります。全角200字以内。",
   q4="ここに不得意なことが入ります。全角200字以内。",
   updated="2026年10月1日"),
]

os.makedirs("src/data", exist_ok=True)
with open("src/data/layouts.csv", "w", encoding="utf-8-sig", newline="") as f:
    w = csv.DictWriter(f, fieldnames=COLS)
    w.writeheader()
    w.writerows(ROWS)
print(f"{len(ROWS)}配列 / {len(COLS)}列 を書き出しました")
